name: Matrix Configurations

on:
    push:
    workflow_dispatch:

jobs:
    deploy-to-ubuntu:
        strategy:
            matrix:
                os: [ubuntu-latest,ubuntu-20.04,windows-latest]
                images: [alpine,hello-world]
                include:
                    - os: ubuntu-latest
                      images: amd64/alpine
                exclude:
                    - os: windows-latest
                      images: alpine
        runs-on: ubuntu-latest
        steps:
            - name: Echo Docker Details
              run: docker info
            - name: Run Image on
              run: docker run hello-worl